### ISSUE TITLE
Training loss = 0 ???

### ISSUE THREAD

**Issue by ChengLung-Jen** [2017-fall-DL-training-program/ImageCaption#23]
Why training loss keeps at 0 ?? I miss something????
logs on terminal (show_attend_tell training):
...
iter 650 (epoch 0), train_loss = 0.00000000, time/batch = 0.28300
Read data: 0.0123600959778
iter 651 (epoch 0), train_loss = 0.00000000, time/batch = 0.29335
Read data: 0.0130391120911
iter 652 (epoch 0), train_loss = 0.00000000, time/batch = 0.28998
Read data: 0.0124900341034
iter 653 (epoch 0), train_loss = 0.00000000, time/batch = 0.27567
Read data: 0.0125939846039
iter 654 (epoch 0), train_loss = 0.00000000, time/batch = 0.28949
Read data: 0.0112497806549
iter 655 (epoch 0), train_loss = 0.00000000, time/batch = 0.28857
Read data: 0.0115580558777
iter 656 (epoch 0), train_loss = 0.00000000, time/batch = 0.29858
Read data: 0.0115931034088
iter 657 (epoch 0), train_loss = 0.00000000, time/batch = 0.27390
Read data: 0.0110268592834
iter 658 (epoch 0), train_loss = 0.00000000, time/batch = 0.28936
Read data: 0.0111567974091
iter 659 (epoch 0), train_loss = 0.00000000, time/batch = 0.28969
Read data: 0.011697769165
iter 660 (epoch 0), train_loss = 0.00000000, time/batch = 0.26498
Read data: 0.0116131305695
iter 661 (epoch 0), train_loss = 0.00000000, time/batch = 0.28810
Read data: 0.0111148357391
iter 662 (epoch 0), train_loss = 0.00000000, time/batch = 0.28152
Read data: 0.0110149383545
iter 663 (epoch 0), train_loss = 0.00000000, time/batch = 0.28879
Read data: 0.0128998756409
iter 664 (epoch 0), train_loss = 0.00000000, time/batch = 0.28138
Read data: 0.0128710269928
iter 665 (epoch 0), train_loss = 0.00000000, time/batch = 0.28916
Read data: 0.0122470855713
iter 666 (epoch 0), train_loss = 0.00000000, time/batch = 0.28179
Read data: 0.0118868350983
iter 667 (epoch 0), train_loss = 0.00000000, time/batch = 0.28896
Read data: 0.0126791000366
iter 668 (epoch 0), train_loss = 0.00000000, time/batch = 0.29050
...
...
...
Read data: 0.0127050876617
iter 5999 (epoch 0), train_loss = 0.00000000, time/batch = 0.28958
Traceback (most recent call last):
  File "train.py", line 235, in <module>
    train(opt)
  File "train.py", line 176, in train
    val_loss, predictions, lang_stats = eval_utils.eval_split(cnn_model, model, crit, loader, eval_kwargs)
  File "/home/leojen/codebase/ai_program/lab2/AI_Training_1108/lab2_image_caption/eval_utils.py", line 119, in eval_split
    alph, seq, _ = model.sample(fc_feats, att_feats, eval_kwargs)
  File "/home/leojen/codebase/ai_program/lab2/AI_Training_1108/lab2_image_caption/models/CaptionModel.py", line 131, in sample
    return alphas, torch.cat([_.unsqueeze(1) for _ in seq], 1), torch.cat([_.unsqueeze(1) for _ in seqLogprobs], 1)
RuntimeError: seq can't be empty

**Comment by connie980149** [comment]
If your model works, the loss will never become 0.
Please run the "show_tell" model first, if the loss is still zero then you need to check your project is correct or not.

**Comment by ChengLung-Jen** [comment]
Please help to check the following error

Traceback (most recent call last):
  File "train.py", line 235, in <module>
    train(opt)
  File "train.py", line 143, in train
    loss = crit(model_output, labels[:,1:], masks[:,1:])
  File "/home/leojen/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/leojen/codebase/ai_program/lab2/AI_Training_1108/lab2_image_caption/misc/utils.py", line 101, in forward
    print(input.gather(1, target))
  File "/home/leojen/.local/lib/python2.7/site-packages/torch/autograd/variable.py", line 684, in gather
    return Gather.apply(self, dim, index)
  File "/home/leojen/.local/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 560, in forward
    return input.gather(dim, index)
RuntimeError: invalid argument 2: Input tensor must have same size as output tensor apart from the specified dimension at /pytorch/torch/lib/THC/generic/THCTensorScatterGather.cu:29
-------------------------------------------
It seems dim not correct?

in class LanguageModelCriterion(nn.Module):
original size 
input: (1L, 17L, 50L, 9488L)
target: (50L, 17L)
mask: (50L, 17L)

and after following codes
        target = target[:, :input.size(1)]
        mask =  mask[:, :input.size(1)]
        input = to_contiguous(input).view(-1, input.size(3)) # original : to_contiguous(input).view(-1, input.size(2))
        target = to_contiguous(target).view(-1, 1)
        mask = to_contiguous(mask).view(-1, 1)

becomes:
input: (161296L, 50L)
target: (850L, 1L)
mask: (850L, 1L)

And code failed at 
print(input.gather(1, target))
---> RuntimeError: invalid argument 2: Input tensor must have same size as output tensor apart from the specified dimension at /pytorch/torch/lib/THC/generic/THCTensorScatterGather.cu:29

**Comment by connie980149** [comment]
That seems your output of ShowAttendTellCore is incorrect. 
The size of input in LanguageModelCriterion is (50L, 17L, 9488L)
