### ISSUE TITLE
Problem of "No module named pycocotools.coco"

### ISSUE THREAD

**Issue by Peter-Chuang** [2017-fall-DL-training-program/ImageCaption#5]
Dear TA,

When I using the caption model with show_tell for training, I got this error message after validation. Did I miss some steps?

Traceback (most recent call last):
  File "train.py", line 256, in <module>
    train(opt)
  File "train.py", line 197, in train
    val_loss, predictions, lang_stats = eval_utils.eval_split(cnn_model, model, crit, loader, eval_kwargs)
  File "/home/student01/Lab2/cp_lab2_image_caption/eval_utils.py", line 185, in eval_split
    lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
  File "/home/student01/Lab2/cp_lab2_image_caption/eval_utils.py", line 32, in language_eval
    from pycocotools.coco import COCO
ImportError: No module named pycocotools.coco

**Comment by Peter-Chuang** [comment]
oh... I forgot to copy the "coco-caption/" to my working directory... 
sorry, this issue is fixed....
